### ISSUE TITLE
Updates will be needed 24 July

### ISSUE THREAD

**Issue by karenword** [jcoliver/auto-demo-email#2]
Heads up that the template email in this repo will need to be updated to reflect changes to our checkout requirements, with anticipated rollout of 24 July. 

Draft changes to the template in The Carpentries Handbook may be found in this PR: https://github.com/carpentries/docs.carpentries.org/pull/912/files

**Comment by jcoliver** [comment]
:cactus:

**Comment by karenword** [comment]
New rollout date of 14 August should be firm!

**Comment by karenword** [comment]
We will be notifying trainees signed up for demos during rollout week in advance, so 7 August might be a better timeline for updates here.

**Comment by jcoliver** [comment]
Addressed in #3 .
